//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpeechRecognition
{
    using System;
    using System.Collections.Generic;
    
    public partial class detail
    {
        public int details_id { get; set; }
        public Nullable<int> customer_id { get; set; }
        public string car_model { get; set; }
        public string car_colour { get; set; }
        public Nullable<int> car_year { get; set; }
        public Nullable<decimal> budget { get; set; }
        public Nullable<bool> car_condition { get; set; }
    }
}
