//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace SpeechRecognition
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class icersEntities1 : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new icersEntities1 object using the connection string found in the 'icersEntities1' section of the application configuration file.
        /// </summary>
        public icersEntities1() : base("name=icersEntities1", "icersEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new icersEntities1 object.
        /// </summary>
        public icersEntities1(string connectionString) : base(connectionString, "icersEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new icersEntities1 object.
        /// </summary>
        public icersEntities1(EntityConnection connection) : base(connection, "icersEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<car> cars
        {
            get
            {
                if ((_cars == null))
                {
                    _cars = base.CreateObjectSet<car>("cars");
                }
                return _cars;
            }
        }
        private ObjectSet<car> _cars;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<customer> customers
        {
            get
            {
                if ((_customers == null))
                {
                    _customers = base.CreateObjectSet<customer>("customers");
                }
                return _customers;
            }
        }
        private ObjectSet<customer> _customers;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<detail> details
        {
            get
            {
                if ((_details == null))
                {
                    _details = base.CreateObjectSet<detail>("details");
                }
                return _details;
            }
        }
        private ObjectSet<detail> _details;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<match> matches
        {
            get
            {
                if ((_matches == null))
                {
                    _matches = base.CreateObjectSet<match>("matches");
                }
                return _matches;
            }
        }
        private ObjectSet<match> _matches;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<weight> weights
        {
            get
            {
                if ((_weights == null))
                {
                    _weights = base.CreateObjectSet<weight>("weights");
                }
                return _weights;
            }
        }
        private ObjectSet<weight> _weights;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the cars EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTocars(car car)
        {
            base.AddObject("cars", car);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the customers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTocustomers(customer customer)
        {
            base.AddObject("customers", customer);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the details EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTodetails(detail detail)
        {
            base.AddObject("details", detail);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the matches EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTomatches(match match)
        {
            base.AddObject("matches", match);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the weights EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToweights(weight weight)
        {
            base.AddObject("weights", weight);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="icersModel", Name="car")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class car : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new car object.
        /// </summary>
        /// <param name="car_id">Initial value of the car_id property.</param>
        public static car Createcar(global::System.Int32 car_id)
        {
            car car = new car();
            car.car_id = car_id;
            return car;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 car_id
        {
            get
            {
                return _car_id;
            }
            set
            {
                if (_car_id != value)
                {
                    Oncar_idChanging(value);
                    ReportPropertyChanging("car_id");
                    _car_id = StructuralObject.SetValidValue(value, "car_id");
                    ReportPropertyChanged("car_id");
                    Oncar_idChanged();
                }
            }
        }
        private global::System.Int32 _car_id;
        partial void Oncar_idChanging(global::System.Int32 value);
        partial void Oncar_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> brand_id
        {
            get
            {
                return _brand_id;
            }
            set
            {
                Onbrand_idChanging(value);
                ReportPropertyChanging("brand_id");
                _brand_id = StructuralObject.SetValidValue(value, "brand_id");
                ReportPropertyChanged("brand_id");
                Onbrand_idChanged();
            }
        }
        private Nullable<global::System.Int32> _brand_id;
        partial void Onbrand_idChanging(Nullable<global::System.Int32> value);
        partial void Onbrand_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String colour
        {
            get
            {
                return _colour;
            }
            set
            {
                OncolourChanging(value);
                ReportPropertyChanging("colour");
                _colour = StructuralObject.SetValidValue(value, true, "colour");
                ReportPropertyChanged("colour");
                OncolourChanged();
            }
        }
        private global::System.String _colour;
        partial void OncolourChanging(global::System.String value);
        partial void OncolourChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, true, "name");
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> condition
        {
            get
            {
                return _condition;
            }
            set
            {
                OnconditionChanging(value);
                ReportPropertyChanging("condition");
                _condition = StructuralObject.SetValidValue(value, "condition");
                ReportPropertyChanged("condition");
                OnconditionChanged();
            }
        }
        private Nullable<global::System.Int16> _condition;
        partial void OnconditionChanging(Nullable<global::System.Int16> value);
        partial void OnconditionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String description
        {
            get
            {
                return _description;
            }
            set
            {
                OndescriptionChanging(value);
                ReportPropertyChanging("description");
                _description = StructuralObject.SetValidValue(value, true, "description");
                ReportPropertyChanged("description");
                OndescriptionChanged();
            }
        }
        private global::System.String _description;
        partial void OndescriptionChanging(global::System.String value);
        partial void OndescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> model
        {
            get
            {
                return _model;
            }
            set
            {
                OnmodelChanging(value);
                ReportPropertyChanging("model");
                _model = StructuralObject.SetValidValue(value, "model");
                ReportPropertyChanged("model");
                OnmodelChanged();
            }
        }
        private Nullable<global::System.Int32> _model;
        partial void OnmodelChanging(Nullable<global::System.Int32> value);
        partial void OnmodelChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="icersModel", Name="customer")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class customer : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new customer object.
        /// </summary>
        /// <param name="customer_id">Initial value of the customer_id property.</param>
        public static customer Createcustomer(global::System.Int32 customer_id)
        {
            customer customer = new customer();
            customer.customer_id = customer_id;
            return customer;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 customer_id
        {
            get
            {
                return _customer_id;
            }
            set
            {
                if (_customer_id != value)
                {
                    Oncustomer_idChanging(value);
                    ReportPropertyChanging("customer_id");
                    _customer_id = StructuralObject.SetValidValue(value, "customer_id");
                    ReportPropertyChanged("customer_id");
                    Oncustomer_idChanged();
                }
            }
        }
        private global::System.Int32 _customer_id;
        partial void Oncustomer_idChanging(global::System.Int32 value);
        partial void Oncustomer_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, true, "name");
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> contact
        {
            get
            {
                return _contact;
            }
            set
            {
                OncontactChanging(value);
                ReportPropertyChanging("contact");
                _contact = StructuralObject.SetValidValue(value, "contact");
                ReportPropertyChanged("contact");
                OncontactChanged();
            }
        }
        private Nullable<global::System.Int64> _contact;
        partial void OncontactChanging(Nullable<global::System.Int64> value);
        partial void OncontactChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> details_id
        {
            get
            {
                return _details_id;
            }
            set
            {
                Ondetails_idChanging(value);
                ReportPropertyChanging("details_id");
                _details_id = StructuralObject.SetValidValue(value, "details_id");
                ReportPropertyChanged("details_id");
                Ondetails_idChanged();
            }
        }
        private Nullable<global::System.Int32> _details_id;
        partial void Ondetails_idChanging(Nullable<global::System.Int32> value);
        partial void Ondetails_idChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="icersModel", Name="detail")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class detail : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new detail object.
        /// </summary>
        /// <param name="details_id">Initial value of the details_id property.</param>
        public static detail Createdetail(global::System.Int32 details_id)
        {
            detail detail = new detail();
            detail.details_id = details_id;
            return detail;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 details_id
        {
            get
            {
                return _details_id;
            }
            set
            {
                if (_details_id != value)
                {
                    Ondetails_idChanging(value);
                    ReportPropertyChanging("details_id");
                    _details_id = StructuralObject.SetValidValue(value, "details_id");
                    ReportPropertyChanged("details_id");
                    Ondetails_idChanged();
                }
            }
        }
        private global::System.Int32 _details_id;
        partial void Ondetails_idChanging(global::System.Int32 value);
        partial void Ondetails_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> customer_id
        {
            get
            {
                return _customer_id;
            }
            set
            {
                Oncustomer_idChanging(value);
                ReportPropertyChanging("customer_id");
                _customer_id = StructuralObject.SetValidValue(value, "customer_id");
                ReportPropertyChanged("customer_id");
                Oncustomer_idChanged();
            }
        }
        private Nullable<global::System.Int32> _customer_id;
        partial void Oncustomer_idChanging(Nullable<global::System.Int32> value);
        partial void Oncustomer_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String car_model
        {
            get
            {
                return _car_model;
            }
            set
            {
                Oncar_modelChanging(value);
                ReportPropertyChanging("car_model");
                _car_model = StructuralObject.SetValidValue(value, true, "car_model");
                ReportPropertyChanged("car_model");
                Oncar_modelChanged();
            }
        }
        private global::System.String _car_model;
        partial void Oncar_modelChanging(global::System.String value);
        partial void Oncar_modelChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String car_colour
        {
            get
            {
                return _car_colour;
            }
            set
            {
                Oncar_colourChanging(value);
                ReportPropertyChanging("car_colour");
                _car_colour = StructuralObject.SetValidValue(value, true, "car_colour");
                ReportPropertyChanged("car_colour");
                Oncar_colourChanged();
            }
        }
        private global::System.String _car_colour;
        partial void Oncar_colourChanging(global::System.String value);
        partial void Oncar_colourChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> car_year
        {
            get
            {
                return _car_year;
            }
            set
            {
                Oncar_yearChanging(value);
                ReportPropertyChanging("car_year");
                _car_year = StructuralObject.SetValidValue(value, "car_year");
                ReportPropertyChanged("car_year");
                Oncar_yearChanged();
            }
        }
        private Nullable<global::System.Int32> _car_year;
        partial void Oncar_yearChanging(Nullable<global::System.Int32> value);
        partial void Oncar_yearChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> budget
        {
            get
            {
                return _budget;
            }
            set
            {
                OnbudgetChanging(value);
                ReportPropertyChanging("budget");
                _budget = StructuralObject.SetValidValue(value, "budget");
                ReportPropertyChanged("budget");
                OnbudgetChanged();
            }
        }
        private Nullable<global::System.Decimal> _budget;
        partial void OnbudgetChanging(Nullable<global::System.Decimal> value);
        partial void OnbudgetChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> car_condition
        {
            get
            {
                return _car_condition;
            }
            set
            {
                Oncar_conditionChanging(value);
                ReportPropertyChanging("car_condition");
                _car_condition = StructuralObject.SetValidValue(value, "car_condition");
                ReportPropertyChanged("car_condition");
                Oncar_conditionChanged();
            }
        }
        private Nullable<global::System.Boolean> _car_condition;
        partial void Oncar_conditionChanging(Nullable<global::System.Boolean> value);
        partial void Oncar_conditionChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="icersModel", Name="match")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class match : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new match object.
        /// </summary>
        /// <param name="match_id">Initial value of the match_id property.</param>
        public static match Creatematch(global::System.Int32 match_id)
        {
            match match = new match();
            match.match_id = match_id;
            return match;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 match_id
        {
            get
            {
                return _match_id;
            }
            set
            {
                if (_match_id != value)
                {
                    Onmatch_idChanging(value);
                    ReportPropertyChanging("match_id");
                    _match_id = StructuralObject.SetValidValue(value, "match_id");
                    ReportPropertyChanged("match_id");
                    Onmatch_idChanged();
                }
            }
        }
        private global::System.Int32 _match_id;
        partial void Onmatch_idChanging(global::System.Int32 value);
        partial void Onmatch_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> customer_id
        {
            get
            {
                return _customer_id;
            }
            set
            {
                Oncustomer_idChanging(value);
                ReportPropertyChanging("customer_id");
                _customer_id = StructuralObject.SetValidValue(value, "customer_id");
                ReportPropertyChanged("customer_id");
                Oncustomer_idChanged();
            }
        }
        private Nullable<global::System.Int32> _customer_id;
        partial void Oncustomer_idChanging(Nullable<global::System.Int32> value);
        partial void Oncustomer_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> car_id
        {
            get
            {
                return _car_id;
            }
            set
            {
                Oncar_idChanging(value);
                ReportPropertyChanging("car_id");
                _car_id = StructuralObject.SetValidValue(value, "car_id");
                ReportPropertyChanged("car_id");
                Oncar_idChanged();
            }
        }
        private Nullable<global::System.Int32> _car_id;
        partial void Oncar_idChanging(Nullable<global::System.Int32> value);
        partial void Oncar_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> priority
        {
            get
            {
                return _priority;
            }
            set
            {
                OnpriorityChanging(value);
                ReportPropertyChanging("priority");
                _priority = StructuralObject.SetValidValue(value, "priority");
                ReportPropertyChanged("priority");
                OnpriorityChanged();
            }
        }
        private Nullable<global::System.Int16> _priority;
        partial void OnpriorityChanging(Nullable<global::System.Int16> value);
        partial void OnpriorityChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="icersModel", Name="weight")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class weight : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new weight object.
        /// </summary>
        /// <param name="weight_id">Initial value of the weight_id property.</param>
        public static weight Createweight(global::System.Int32 weight_id)
        {
            weight weight = new weight();
            weight.weight_id = weight_id;
            return weight;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 weight_id
        {
            get
            {
                return _weight_id;
            }
            set
            {
                if (_weight_id != value)
                {
                    Onweight_idChanging(value);
                    ReportPropertyChanging("weight_id");
                    _weight_id = StructuralObject.SetValidValue(value, "weight_id");
                    ReportPropertyChanged("weight_id");
                    Onweight_idChanged();
                }
            }
        }
        private global::System.Int32 _weight_id;
        partial void Onweight_idChanging(global::System.Int32 value);
        partial void Onweight_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> customer_id
        {
            get
            {
                return _customer_id;
            }
            set
            {
                Oncustomer_idChanging(value);
                ReportPropertyChanging("customer_id");
                _customer_id = StructuralObject.SetValidValue(value, "customer_id");
                ReportPropertyChanged("customer_id");
                Oncustomer_idChanged();
            }
        }
        private Nullable<global::System.Int32> _customer_id;
        partial void Oncustomer_idChanging(Nullable<global::System.Int32> value);
        partial void Oncustomer_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> car_id
        {
            get
            {
                return _car_id;
            }
            set
            {
                Oncar_idChanging(value);
                ReportPropertyChanging("car_id");
                _car_id = StructuralObject.SetValidValue(value, "car_id");
                ReportPropertyChanged("car_id");
                Oncar_idChanged();
            }
        }
        private Nullable<global::System.Int32> _car_id;
        partial void Oncar_idChanging(Nullable<global::System.Int32> value);
        partial void Oncar_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> made
        {
            get
            {
                return _made;
            }
            set
            {
                OnmadeChanging(value);
                ReportPropertyChanging("made");
                _made = StructuralObject.SetValidValue(value, "made");
                ReportPropertyChanged("made");
                OnmadeChanged();
            }
        }
        private Nullable<global::System.Decimal> _made;
        partial void OnmadeChanging(Nullable<global::System.Decimal> value);
        partial void OnmadeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> company
        {
            get
            {
                return _company;
            }
            set
            {
                OncompanyChanging(value);
                ReportPropertyChanging("company");
                _company = StructuralObject.SetValidValue(value, "company");
                ReportPropertyChanged("company");
                OncompanyChanged();
            }
        }
        private Nullable<global::System.Decimal> _company;
        partial void OncompanyChanging(Nullable<global::System.Decimal> value);
        partial void OncompanyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> colour
        {
            get
            {
                return _colour;
            }
            set
            {
                OncolourChanging(value);
                ReportPropertyChanging("colour");
                _colour = StructuralObject.SetValidValue(value, "colour");
                ReportPropertyChanged("colour");
                OncolourChanged();
            }
        }
        private Nullable<global::System.Decimal> _colour;
        partial void OncolourChanging(Nullable<global::System.Decimal> value);
        partial void OncolourChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> price
        {
            get
            {
                return _price;
            }
            set
            {
                OnpriceChanging(value);
                ReportPropertyChanging("price");
                _price = StructuralObject.SetValidValue(value, "price");
                ReportPropertyChanged("price");
                OnpriceChanged();
            }
        }
        private Nullable<global::System.Decimal> _price;
        partial void OnpriceChanging(Nullable<global::System.Decimal> value);
        partial void OnpriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> condition
        {
            get
            {
                return _condition;
            }
            set
            {
                OnconditionChanging(value);
                ReportPropertyChanging("condition");
                _condition = StructuralObject.SetValidValue(value, "condition");
                ReportPropertyChanged("condition");
                OnconditionChanged();
            }
        }
        private Nullable<global::System.Decimal> _condition;
        partial void OnconditionChanging(Nullable<global::System.Decimal> value);
        partial void OnconditionChanged();

        #endregion

    }

    #endregion

}
