//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpeechRecognition
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class icersEntities1 : DbContext
    {
        public icersEntities1()
            : base("name=icersEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<car> cars { get; set; }
        public DbSet<customer> customers { get; set; }
        public DbSet<detail> details { get; set; }
        public DbSet<match> matches { get; set; }
        public DbSet<weight> weights { get; set; }
    }
}
